### ISSUE TITLE
Support for IReadOnlyDictionary<string, object>

### ISSUE THREAD

**Issue by agrinei** [zachsaw/Binaron.Serializer#22]
Serializer already handles IDictionary<string, object> properly. It would be nice if it had support for IReadOnlyDictionary<string, object> too.

Better yet if it could also work with IReadOnlyDictionary<string, IReadOnlyDictionary<string, object>> :-)

**Comment by zachsawcs** [comment]
Good find! I'll add support for IReadOnlyDictionary. It's a pity .net's IDictionary doesn't implement IReadOnlyDictionary. Would make life a lot easier for a serializer.

**Comment by zachsaw** [comment]
Done. https://github.com/zachsaw/Binaron.Serializer/releases/tag/nuget-2.3.0

**Comment by agrinei** [comment]
Wow, that was quick! Thank you very much! 👍 

"It's a pity .net's IDictionary doesn't implement IReadOnlyDictionary."
So true! And it's the same with IList and IReadOnlyList :/
