### ISSUE TITLE
Problem when working with DateTime type

### ISSUE THREAD

**Issue by rintoz** [zachsaw/Binaron.Serializer#24]
When serialized a DateTime object and deserialized, resulted DateTime is in UTC instead of local DateTime. The object clearly shows the Kind is Utc instead of Local.

**Comment by zachsaw** [comment]
The storage format is created to be widely compatible with other languages** and thus the need to pick the lowest common denominator. I could perhaps provide users with an option to treat DateTime as a POCO which will allow you to serialize it as stored in memory. Another option I might add that is orthogonal to this is to have an option to convert UTC to local time in the deserializer option. Both will be opt-in.

** e.g. in Python, the Naive datetime object does not carry any info about its locale.

**Comment by zachsaw** [comment]
I've added a DeserializerOption to convert DateTime to your TimeZoneInfo of your choice in v2.4.0.

e.g. To convert to local time, use the following
`new DeserializerOptions {TimeZoneInfo = TimeZoneInfo.Local}`

**Comment by rintoz** [comment]
I understand the reason for getting back DateTime in UTC format. The option provided is neat and clean, worked as expected. I am using Binaron for serialize/deserialize for caching.  Now with this configuration I don't have to use additional code to convert date to local format. Appreciate your help. 

Thank you so much.

**Comment by rintoz** [comment]
I understand the reason for getting back DateTime in UTC format. The option provided is neat and clean, worked as expected. I am using Binaron for serialize/deserialize for caching.  Now with this configuration I don't have to use additional code to convert date to local format. Appreciate your help. 

Thank you so much.
